### ISSUE TITLE
Logging of messages to stdout

### ISSUE THREAD

**Issue by mlafeldt** [donovanhide/eventsource#16]
Hi,

We're using eventsource for streaming logs from a remote API to a local command-line client, which works great in general.

Unfortunately, the library currently logs to stdout at two places:

- https://github.com/donovanhide/eventsource/blob/8c5962c7c1f7c559669b83d28370b5003c6a8a7f/stream.go#L127
- https://github.com/donovanhide/eventsource/blob/8c5962c7c1f7c559669b83d28370b5003c6a8a7f/server.go#L90

At least the first one is annoying since the message will be printed along the normal logs we're streaming.

What do you think about either removing the log message or making it optional? Both would be fine for us.

/cc @seiffert

**Comment by donovanhide** [comment]
Hi,
yep the logs are a wart, although occasionally a useful one :-) 

How about adding a ```Debug bool``` field to both the `Server` and the `Stream` structs and only log if true?

**Comment by mlafeldt** [comment]
Yeah, that would do the job!

**Comment by donovanhide** [comment]
Want to do the pull request?

**Comment by mlafeldt** [comment]
Yes, give me a minute. :)

**Comment by mlafeldt** [comment]
@donovanhide What do you think about #17?

**Comment by donovanhide** [comment]
Looks good,thanks :-) 
If only log.Logger was an interface rather than a struct, the world would be a better place!

https://golang.org/pkg/log/#Logger

**Comment by mlafeldt** [comment]
Thanks, man!
