### ISSUE TITLE
Contributing preferences

### ISSUE THREAD

**Issue by kcollasarundell** [donovanhide/eventsource#27]
Hi, We use this library at work and i have made a bunch of somewhat hacky changes to our fork that i would like to eventually upstream. These have mainly been around ensuring it doesn't leak goroutines and supports contexts for canceling requests when complete or no longer required.

I am just wondering if you have any preference on how i submit PRs (or if i do)

**Comment by donovanhide** [comment]
Sure, just make them less hacky (i.e. documented) and open some PR's :-)
