### ISSUE TITLE
Close() for subscriptions.

### ISSUE THREAD

**Issue by shanna** [donovanhide/eventsource#6]
I notice there isn't a way to `Close()` a subscription at the moment (or am I missing something?). I'm happy to do the work and submit a pull request but I thought I'd ask here first if you had an approach in mind since `Decode()` blocks and you may not want to wait till after the next event to close the connection and exit the `stream()` loop.

**Comment by phemmer** [comment]
PR for this over at #10

**Comment by archer-fengjiang** [comment]
Stream is leaking file descriptor as I found it out in production. What's the reason #10 was closed? @phemmer

**Comment by sybrandy** [comment]
Will there be any progress regarding this?  The fact that goroutines can leak can be an issue in long-running apps and even if the use case isn't "typical", it's a good practice to ensure it doesn't happen.

**Comment by donovanhide** [comment]
@phemmer @sybrandy @archer-fengjiang If any of you want to re-visit #10, happy to review it :-)

**Comment by sybrandy** [comment]
@donovanhide I patched my copy of the code with the fix in #10 and I'll let you know what happens.  I'm running a long-running service, but I missed a line in the close method when I patched it, so it crashed randomly.  It's fixed now and I'm running it again.  I'll let you know the status after I let it run for some time.

**Comment by sybrandy** [comment]
So, I let my code run over the weekend and the goroutines have not gotten out of control.  In fact, the number of goroutines that exist at any time appears to only vary by 4.  Granted, I don't know what else is creating them (lots of code that I didn't create), but from what I can tell, this patch is working.

I did not run the test that is in the PR, so I don't know what the state of it is, but assuming the test covers everything it needs to, I think this is good to go.

**Comment by marco-jantke** [comment]
I am currently trying to fix the [go-marathon issue](https://github.com/gambol99/go-marathon/issues/212). Therefore I had a deep look now into this library, as its used by go-marathon to establish the SSE subscription. I am wondering why the promising initiatives to implement the `Close()` have been stopped. I see that #10 actually looked good and also @donovanhide branch https://github.com/donovanhide/eventsource/tree/stream-close looks promising. 

@donovanhide any chance that you will continue working on this? How can we help getting this issue done?

Just as a side note: the only other option I have at the moment to implement the failover to another node is to pass an HTTP-Client with my own implemented Transport, which will change the request URL.. This said, I think there are more use-cases for the Close() and it would be very valuable to have it in the library.

**Comment by donovanhide** [comment]
Hi @marco-jantke,

sorry for the inactivity, been very busy with other work. If you want to give a review to that branch and respond to the comments raised and perhaps address them with a separate PR, I'd be happy to merge :-)

**Comment by marco-jantke** [comment]
That sounds good, so I am currently preparing a PR for this. Hope to be able to submit tomorrow :)
