### ISSUE TITLE
eventsource stream does not handle "101:Switching Protocols"

### ISSUE THREAD

**Issue by amoghe** [donovanhide/eventsource#9]
Some server implementations of SSE/eventsource will send a 101:Switching Protocols followed by a 200:OK , followed by the stream of events.

This does not play well with this implementation because 

```
if resp.StatusCode != 200 {
		message, _ := ioutil.ReadAll(resp.Body)
		err = SubscriptionError{
			Code:    resp.StatusCode,
			Message: string(message),
		}
	}
```

will choke on the first 101 response.

I believe this is something clients should be able to handle because this does not seem to violate the spec.

Unfortunately I don't think there is an easy way to rework this using golang's http client. Other language implementations that I've seen (notably, ruby) seem to rely on parsing the http response themselves, thereby handling the possible 101 response that precedes the 200.

**Comment by donovanhide** [comment]
Feel free to reopen if this still an issue :-)
